import VideoPlayer from "../components/VideoPlayer";
import VideoInfo from "../components/VideoInfo";
import React, {useState} from "react";
import {useParams} from "react-router-dom";

function Watch() {
  //const [data, setData] = useState({ loading:true, video:null });
  const {id} = useParams();
  const [data, setData] = useState({ loading:true, video: {
    src: "",
    meta: {
      id: 1,
      thumbnailUrl:"https://i.ytimg.com/vi/5U-JroWwFkw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDKTRzb_VIrOHoYN05f1muzfdJ_yQ",
      runtime:2445,
      title:"Lost Stars",
      viewCnt:2834,
      createAt: 1627299209433,
      description: `Provided to YouTube by Universal Music Group

Lost Stars · Adam Levine

Begin Again - Music From And Inspired By The Original Motion Picture

℗ 2014 Interscope Records

Released on: 2014-07-01

Producer: Gregg Alexander
Composer  Lyricist: Gregg Alexander
Composer  Lyricist: Danielle Brisebois
Composer  Lyricist: Nick Lashley
Composer  Lyricist: Nick Southwood

Auto-generated by YouTube.`,
      creator: {
        name:"Adam Levine - 주제",
        profileImageUrl: "https://yt3.ggpht.com/wM16Xbm-Sy4vKcoSID62TkowXq8wR7Rn76GVjjPCrjskpAEZ4NBUxB3K1xi31cZKRp-gISHXhg=s48-c-k-c0x00ffffff-no-rj",
      }
    }
  }});


  return (
    <div>
      {
        /* (data.loading==true || data.video!=null) ? */
        (false) ? 
          <div>loading 중입니다</div> 
          : 
        (
          <>
            <VideoPlayer src={data.viedo?.src} />
            <VideoInfo meta={data.video?.meta} a="123" b="2132"/>
          </>
        )
      }
    </div>
  );
}

export default Watch;
